const fs = require('fs');
const path = require('path');

const wwwDir = path.join(__dirname, '../www');
const jsConfigPath = path.join(wwwDir, 'frontend/js/config.js');
const indexHtmlPath = path.join(wwwDir, 'index.html');

// Replace the entire config.js with a hardcoded mobile version
// This is the safest approach - no regex matching required
const mobileConfig = `// MOBILE BUILD - Auto-generated by prep-web.js
const CONFIG = {
    BASE_PATH: '',
    API_BASE_URL: 'https://ahmedmagdy.com/pl/backend/api',
    LIVE_URL: 'https://ahmedmagdy.com/pl',
    APP_ENV: 'production'
};
`;

if (fs.existsSync(jsConfigPath)) {
    fs.writeFileSync(jsConfigPath, mobileConfig);
    console.log('✅ config.js replaced with mobile-specific version');
}

// Update index.html base href
if (fs.existsSync(indexHtmlPath)) {
    let content = fs.readFileSync(indexHtmlPath, 'utf8');
    content = content.replace(/<base href="[^"]*">/g, '<base href="./">');
    fs.writeFileSync(indexHtmlPath, content);
    console.log('✅ index.html base href set to ./');
}

console.log('✅ Mobile build preparation complete!');
